inherit_from: .rubocop_todo.yml

inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'
  - 'db/**/*'
  - 'spec/**/*'
  - 'lib/tasks/**/*'
  - 'config/**/*'

Metrics/ClassLength:
  Exclude:
  - 'app/controllers/catalog_controller.rb'
  - 'lib/psulib_blacklight/solr_manager.rb'

Layout/LineLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/components/browse/*'
    - 'app/components/external_links/*'
    - 'app/models/concerns/null_object_pattern.rb'

Rails/ContentTag:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'

RSpec/NestedGroups:
  Enabled: false
  
Capybara/FeatureMethods:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
