require: rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'
  - 'db/**/*'
  - 'spec/**/*'
  - 'lib/tasks/**/*'
  - 'config/**/*'

Metrics/ClassLength:
  Exclude:
  - 'app/controllers/catalog_controller.rb'
  - 'lib/psulib_blacklight/solr_manager.rb'
  - 'app/presenters/shelf_list_presenter.rb'
  - 'app/services/shelf_list.rb'

Layout/LineLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'
  - 'spec/controllers/catalog_controller_spec.rb'
  - 'app/components/blacklight/advanced_search_form_component.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/components/browse/*'
    - 'app/components/external_links/*'
    - 'app/models/concerns/null_object_pattern.rb'

Metrics/CyclomaticComplexity:
  Exclude:
  - 'app/components/psul_search_bar_component.rb'
  - 'app/components/blacklight/document/action_component.rb'

Metrics/PerceivedComplexity:
  Exclude:
  - 'app/components/blacklight/document/action_component.rb'

Rails/ContentTag:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'

RSpec/NestedGroups:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/Capybara:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
  - 'spec/features/google_preview_link_spec.rb'
  - 'spec/components/browse/call_number_navigation_spec.rb'
  - 'spec/components/browse/facet_navigation_spec.rb'
  - 'spec/components/browse/page_size_selector_spec.rb'
  - 'spec/components/browse/prefix_selector_spec.rb'
  - 'spec/features/hathi_link_spec.rb'

RSpec/RepeatedExampleGroupBody:
  Exclude:
  - 'spec/features/google_preview_link_spec.rb'
  - 'spec/features/hathi_link_spec.rb'

RSpec/MessageSpies:
  Exclude:
  - 'spec/controllers/catalog_controller_spec.rb'

Style/FrozenStringLiteralComment:
  Exclude:
  - 'spec/models/search_builder_spec.rb'
