inherit_from: .rubocop_todo.yml

inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'
  - 'db/**/*'
  - 'spec/**/*'
  - 'lib/tasks/**/*'

Metrics/LineLength:
  Exclude:
  # The catalog controller is just one giant block for config.
  - 'app/controllers/catalog_controller.rb'

RSpec/MultipleExpectations:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
  # Feature specs are special.
  - 'spec/features/**/*'
  
Capybara/FeatureMethods:
  Enabled: false
