# scss-lint config file

# Lint all scss files
scss_files: "**/*.scss"

# Files to exclude
exclude:
  - 'vendor/*'
  - 'node_modules/**/*'
  - 'app/javascript/psulib_blacklight/styles/_callouts.scss'
  - 'app/javascript/psulib_blacklight/styles/blacklight_overrides/*'

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning
