development:
  adapter: solr
  url: <%= "#{Settings.solr.url}/solr/#{Settings.solr.collection}" %>
qa:
  adapter: solr
  url: <%= "#{Settings.solr.url}/solr/#{Settings.solr.collection}" %>
test: &test
  adapter: solr
  url: <%= "#{Settings.solr.url}/solr/#{Settings.solr.collection}" %>
production:
  adapter: solr
  url: <%= "#{Settings.solr.url}/solr/#{Settings.solr.collection}" %>
