development:
  adapter: solr
  url: <%= "#{PsulibBlacklight::SolrConfig.new.query_url}" %>
qa:
  adapter: solr
  url: <%= "#{PsulibBlacklight::SolrConfig.new.query_url}" %>
test: &test
  adapter: solr
  url: <%= "#{PsulibBlacklight::SolrConfig.new.query_url}" %>
production:
  adapter: solr
  url: <%= "#{PsulibBlacklight::SolrConfig.new.query_url}" %>
