development:
  adapter: solr
  <% if Settings.solr.password %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.username}:#{Settings.solr.password}@#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% else %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% end %>
qa:
  adapter: solr
  <% if Settings.solr.password %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.username}:#{Settings.solr.password}@#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% else %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% end %>
test: &test
  adapter: solr
  <% if Settings.solr.password %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.username}:#{Settings.solr.password}@#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% else %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% end %>
production:
  adapter: solr
  <% if Settings.solr.password %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.username}:#{Settings.solr.password}@#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% else %>
  url: <%= "#{Settings.solr.protocol}://#{Settings.solr.host}:#{Settings.solr.port}/solr/#{Settings.solr.collection}" %>
  <% end %>
